/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hiring.memallook;

import com.hiring.memallook.commands.Initialization;
import picocli.CommandLine;

public class App {
    public static void main(String[] args) {
        System.exit(new CommandLine(new Initialization()).execute(args));
    }
}
