/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hiring.memallook;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appRunsCommandline() {
        App classUnderTest = new App();
    }
}
